highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
github:
  repository_url: https://github.com/messagerie-melanie2

